config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("add/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

rooms/urls.py
import imp
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.AddRoomView.as_view(), name="create"),
    path("<int:pk>", views.Room_Detail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/upload/", views.AddPhotoView.as_view(), name="add-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photos"),
    path("<int:room_pk>/photos/<int:photo_pk>/edit/", views.EditPhotoView.as_view(), name="edit-photo"),
    path("search/", views.search, name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),

    # path("verify/<str:key>/", views.complete_verification, name="complete-verification"),
    path("login/google/", views.google_login, name="google-login"),
    path("login/google/callback/", views.google_callback, name="google-callback"),
    # path("login/facebook/", views.facebook_login, name="facebook-login"),
    # path("login/facebook/callback/", views.facebook_callback, name="facebook-callback"),

    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.PasswordChangeView.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
]

templates/partials/footer.html
<div class="container w-9/12 mx-auto flex items-center justify-center py-2 mt-4 border-t">
    <footer class="text-base font-light">
        &copy; 2022 Nama-Stay
    </footer>
</div>

templates/partials/messages.html
{% if messages %}
<ul class="absolute mx-auto top-0 left-0 right-0 flex justify-center">
    {% for message in messages %}
        <li class=" z-10 font-medium rounded-full text-white py-4 px-6 w-64 text-center animate-messageFadeIn {% if message.tags %}{{message.tags}}{% endif %}">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
{% if user.is_authenticated %}
    <ul class="text-sm font-medium h-full flex justify-end">
        <div class="flex items-center justify-end">
            <li class="nav_link">
                <a href="{% url 'users:switch-hosting' %}">
                    {% if request.session.is_hosting %}
                        Stop hosting
                    {% else %} 
                        Start hosting
                    {% endif %}
                        
                </a>
            </li>
            {% if request.session.is_hosting %}
                <li class="nav_link"><a href="{% url 'rooms:create' %}">Add Room</a></li>
            {% endif %}
            <li class="nav_link"><a href="{{user.get_absolute_url}}">Profile</a></li>
            <li class="nav_link"><a href="{% url 'lists:see-favs' %}">Favs({{user.lists.room.count}})</a></li>
            <li class="nav_link mr-2"><a href="{% url 'users:logout' %}">Log out</a></li>
        </div>
    </ul>
{% else %}
    <ul class="text-sm font-medium h-full flex justify-end">
        <div class="flex items-center justify-end mx-2">
            <li class="nav_link"><a href="{% url 'users:login' %}">Log in</a></li>
            <li class="nav_link mr-2"><a href="{% url 'users:signup' %}">Signup</a></li>
        </div>
    </ul>
{% endif %}

templates/partials/room_card.html
<div class="w-1/3 mb-10 px-4 overflow-hidden">
    <a href="{% url 'rooms:detail' room.pk %}">
        <div class="w-full h-64 bg-cover bg-center rounded-lg mb-3" style="background-image: url({{room.first_photo}});"></div>
        <div class="flex justify-between mb-2 truncate">
            <div class="w-4/5 overflow-hidden flex">
                {% if room.host.superhost %}
                    <span class="mr-2 uppercase font-medium text-xs border border-black text-black rounded px-2 py-px">superhost</span>
                {% endif %}
    
                <span class="text-gray-600 text-sm font-normal block truncate">{{room.city}}, {{room.country.name}}</span>
            </div>
            <span class="text-sm flex items-center">
                <i class="fas fa-star text-red-500 text-xs mr-1"></i> {{room.total_rating}}
            </span>
        </div>
        <span class="text-black w-11/12 block truncate">{{room.name}}</span>
    </a>
</div>

templates/partials/social_login.html
{% load static %}
<div class="flex flex-col items-center">
    <a href="{% url 'users:google-login' %}" class="btn bg-white text-gray-700 mt-9 mb-3 pl-3">
        <div class="flex items-center">
            <img class="mr-10" style="max-width: 7%;" src="{% static 'img/google.png' %}">  Continue with Google
        </div>
    </a>
    <a href="" class="btn bg-white text-gray-700 pl-3">
        <div class="flex items-center">
            <img class="mr-8" style="max-width: 7%;" src="{% static 'img/facebook.png' %}">  Continue with Facebook
        </div>
    </a>
</div>

<div class="flex items-center w-full my-5">
    <div class="h-px w-full bg-gray-400"></div>
    <span class="text-gray-600 text-sm font-medium mx-4">or</span>
    <div class="h-px w-full bg-gray-400"></div>
</div>

{% comment %} <a href="{% url 'users:facebook-login' %}"> {% endcomment %}