config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("add/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

rooms/urls.py
import imp
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.AddRoomView.as_view(), name="create"),
    path("<int:pk>", views.Room_Detail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/upload/", views.AddPhotoView.as_view(), name="add-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photos"),
    path("<int:room_pk>/photos/<int:photo_pk>/edit/", views.EditPhotoView.as_view(), name="edit-photo"),
    path("search/", views.search, name="search"),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from core import models as core_models
from users import models as user_models
from cal import Calendar
from django.utils import timezone


class AbstractItem(core_models.TimeStamped):

    """Abstract Item"""

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):

    """RoomType Model Definition"""

    class Meta:
        verbose_name = "Room Type"
        ordering = ["name"]


class Amenity(AbstractItem):

    """Amentiy Model Definition"""

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    """Facility Model Definition"""

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):

    """House_rule Model Definition"""

    class Meta:
        verbose_name = "House Rule"


class Room(core_models.TimeStamped):

    """Room Model Definition"""

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedroom = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        "users.User", related_name="rooms", on_delete=models.CASCADE
    )
    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenity = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    facility = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    house_rule = models.ManyToManyField("HouseRule", related_name="rooms", blank=True)

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name

    def total_rating(self):
        all_reviews = self.reviews.all()
        total_avg = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                total_avg += review.rating_average()
                return round(total_avg / len(all_reviews), 2)
        return 0
    
    def first_photo(self):
        try:
            photo, = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None
    
    def get_next_photos(self):
        try:
            photos = self.photos.all()[1:5]
            return list(photos)
        except ValueError:
            return None

    def get_calendars(self):
        now = timezone.localtime(timezone.now())
        this_year = now.year
        this_month = now.month
        next_month = now.month + 1
        if this_month ==12:
            next_month = 1
            this_year += 1
        this_month_cal = Calendar(this_year, this_month)
        next_month_cal = Calendar(this_year, next_month)
        return [this_month_cal, next_month_cal]


class Photo(core_models.TimeStamped):

    """Photo Model Definition"""

    caption = models.CharField(max_length=100)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="IN").formfield()
    price = forms.IntegerField(required=False)
    room_type = forms.ModelChoiceField(
        queryset=models.RoomType.objects.all(),
        empty_label="Any Kind",
        required=False,
    )
    guests = forms.IntegerField(required=False)
    bedroom = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    facilities = forms.ModelMultipleChoiceField(
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")
    
    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedroom",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenity",
        "facility",
        "house_rule",
    )

    def save(self, user, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, UpdateView, FormView
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django_countries import countries
from . import models, forms
from users import mixins as user_mixins



class HomeView(ListView):

    """Home View Definition"""

    model = models.Room
    paginate_by = 12
    paginate_orphans = 5
    ordering = "created"


class Room_Detail(DetailView):
    """Detail View Definition"""

    model = models.Room


def search(request):

    country = request.GET.get("country")

    if country:
        form = forms.SearchForm(request.GET)

        if form.is_valid():
            # print(form.cleaned_data)
            city = form.cleaned_data.get("city")
            country = form.cleaned_data.get("country")
            price = form.cleaned_data.get("price")
            room_type = form.cleaned_data.get("room_type")
            guests = form.cleaned_data.get("guests")
            bedroom = form.cleaned_data.get("bedroom")
            beds = form.cleaned_data.get("beds")
            baths = form.cleaned_data.get("baths")
            instant_book = form.cleaned_data.get("instant_book")
            superhost = form.cleaned_data.get("superhost")
            amenities = form.cleaned_data.get("amenities")
            facilities = form.cleaned_data.get("facilities")

            filter_args = {}

            if city != "Anywhere":
                filter_args["city_startswith"] = city

            filter_args["country"] = country

            if room_type is not None:
                filter_args["room_type"] = room_type

            if price is not None:
                filter_args["price__lte"] = price

            if guests is not None:
                filter_args["guests__gte"] = guests

            if bedroom is not None:
                filter_args["bedroom__gte"] = bedroom

            if beds is not None:
                filter_args["beds__gte"] = beds

            if baths is not None:
                filter_args["baths__gte"] = baths

            if instant_book:
                filter_args["instant_book"] = True

            if superhost:
                filter_args["host__superhost"] = True

            for amenity in amenities:
                filter_args["amenity"] = amenity

            for facility in facilities:
                filter_args["facility"] = facility

            qs = models.Room.objects.filter(**filter_args).order_by("-created")

            paginator = Paginator(qs, 10, orphans=5)

            page = request.GET.get("page", 1)

            rooms = paginator.get_page(page)

            return render(request, "rooms/search.html", {"form": form})

    else:
        form = forms.SearchForm()

    return render(request, "rooms/search.html", {"form": form})


class EditRoomView(user_mixins.LoggedInOnlyView, UpdateView):

    model = models.Room
    template_name = "rooms/room_edit.html"
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedroom",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenity",
        "facility",
        "house_rule",
    )

    def get_object(self, queryset=None):
        room =  super().get_object(queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room
    

class RoomPhotosView(user_mixins.LoggedInOnlyView, Room_Detail):

    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room =  super().get_object(queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room

@login_required
def delete_photo(request, room_pk, photo_pk):
    
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "Can't delete that photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo Deleted")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Photo
    template_name = "rooms/photo_edit.html"
    fields = ("caption",)
    pk_url_kwarg = "photo_pk"
    success_message = "Photo Updated"
    
    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class AddPhotoView(user_mixins.LoggedInOnlyView, FormView):

    template_name = "rooms/photo-upload.html"
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get('pk')
        form.save(pk)
        messages.success(self.request, "Photo uploaded")
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class AddRoomView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save(self.request.user)
        room.host = self.request.user
        room.save()
        form.save_m2m()
        messages.success(self.request, "Room added")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))
        

templates/rooms/photo-upload.html
{% extends 'base.html' %}

{% block page_title %}
    Upload Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}


{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-[360px] mx-auto py-8 flex flex-col justify-start border border-gray-400">
        
        {% include 'mixins/room/room_form.html' with form=form submitBtn="Upload Photo" %}
        
    </div>
{% endblock content %}

templates/rooms/photo_edit.html
{% extends 'base.html' %}

{% block page_title %}
    Update Photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}


{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-[360px] mx-auto py-8 flex flex-col justify-start border border-gray-400">
        
        {% include 'mixins/room/room_form.html' with form=form submitBtn="Update Photo" %}
        
    </div>
{% endblock content %}

templates/rooms/room_create.html
{% extends 'base.html' %}

{% block page_title %}
    Create Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}


{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-[360px] mx-auto py-8 flex flex-col justify-start border border-gray-400">
        
        {% include 'mixins/room/room_form.html' with form=form submitBtn="Create Room" %}
        
    </div>
{% endblock content %}

templates/rooms/room_detail.html
{% extends 'base.html' %} 
{% load is_booked on_favs %}
{% block Page_name %} 
  {{room.name}} 
{% endblock Page_name %} 

{% block content %}
  <div class="container w-11/12 mx-auto">
    <div class="w-full flex justify-between  mb-10">
      <div class="">
        <h4 class="text-3xl font-medium mb-px">{{room.name}}</h4>
        <span class="text-gray-700 font-medium">{{room.city}}</span>
      </div>
      <div class="mt-2">
        {% on_favs room as on_favs_bool %}
        {% if on_favs_bool %}
          <a href="{% url 'lists:toggle-room' room.pk %}?action=remove" class="mr-3 px-2">
            <i class="fas fa-solid fa-heart fa-2x text-red-500"></i>
          </a>
        {% else %}
          <a href="{% url 'lists:toggle-room' room.pk %}?action=add" class="mr-3 px-2">
            <i class="far fa-heart fa-2x" style="color:red"></i>
          </a>
        {% endif %}
      </div>
    </div>
  
    <div class="container h-65vh flex mb-20">
      <div class="h-full w-1/2 bg-cover bg-center rounded-l-2xl mr-2" style="background-image:url({{room.first_photo}})" ></div>
      <div class="h-full w-1/2 flex flex-wrap">
        {% for photo in room.get_next_photos  %}
          <div class="rounded-sm {% if forloop.counter <= 2 %}mb-2{% endif %}  {% if forloop.counter == 2 %}rounded-tr-2xl ml-2{% elif forloop.counter == 4 %}rounded-br-2xl ml-2{% endif %} h-auto bg-cover bg-center border border-gray-400" style="width: 48%; background-image:url({{photo.file.url}})"></div>
        {% endfor %}
      </div>
    </div>
  
    <div class="container w-full pb-12 flex justify-between">
      <div class="w-3/5">
        <div class="flex justify-between border-section">

          <div class="w-full flex items-center  mb-5">
            <div class="w-full flex-col">
              <h4 class="text-2xl text-gray-900 font-medium mr-10 mb-2">{{room.room_type}} hosted by {{room.host}}</h4>
              <div class="flex">
                <h5 class="text-teal-700 font-medium text-base">{{room.guests}} guest{{room.guests|pluralize}}</h5>
                <h5 class="text-teal-700 font-medium text-base">&nbsp; {{room.beds}} bed{{room.beds|pluralize}}</h5> 
                <h5 class="text-teal-700 font-medium text-base">&nbsp; {{room.bedroom}} bedroom{{room.bedroom|pluralize}}</h5> 
                <h5 class="text-teal-700 font-medium text-base">&nbsp; {{room.baths}} bath{{room.baths|pluralize}}</h5> 
              </div>
            </div>

            <a href="{{room.host.get_absolute_url}}">
              {% include "mixins/user_avatar.html" with user=room.host %}
            </a>
          </div>
        </div>

        <p class="py-8 border-section">{{room.description}}</p>

        <div class="border-section py-8">
          <h4 class="font-medium text-2xl mb-5">What this place offers</h4>
          <div class="w-full flex flex-wrap">
            {% for a in room.amenity.all %}
              <span class="mr-24 w-1/3 mb-6 text-teal-700 font-medium text-base">{{a}}</span>
            {% endfor %}
          </div>
        </div>

        <div class="border-section py-8">
          <h4 class="font-medium text-2xl mb-5">Other Facilities</h4>
          <div class="w-full flex flex-wrap">
            
            {% if room.facility.count > 0 %}
              {% for f in room.facility.all %}
                <span class="mr-24 w-1/3 mb-6 text-teal-700 font-medium text-base">{{f}}</span>
              {% endfor %}
            {% else %}
              <span class="mb-6 text-black font-medium text-base">No other facility</span>
            {% endif %}
          </div>
        </div>

        <div class="py-8">
          {% if room.house_rule.count > 0 %}
            <h4 class="font-medium text-2xl mb-5">House Rules</h4>
            <div class="w-full flex flex-wrap">
              {% for rule in room.house_rule.all %}
                <span class="mr-24 w-1/3 mb-6 text-teal-700 font-medium text-base">{{rule}}</span>
              {% endfor %}
            </div>
          {% else %}  
            <h4 class="font-medium text-2xl mb-5">No House Rules</h4>
          {% endif %}
        </div>
      </div>
      
      {% comment %} 2nd column {% endcomment %}
      <div class="w-1/3 px-8">
        {% if room.host == user %}
          <a href="{% url 'rooms:edit' room.pk %}" class="w-1/2 btn bg-red-500 text-white block">Edit Room</a>
        {% else %}
          {% if not request.session.is_hosting %}
            {% for calendar in room.get_calendars %}
              <div class="mb-20">  
                <span class="text-center font-semibold text-lg block mb-8">{{calendar.get_month}}/{{calendar.year}}</span>
                <div class="cal-grid font-medium mb-4">
                  {% for day in calendar.day_names %}
                    <span>{{day}}</span>
                  {% endfor %}
                </div>
                <div class="cal-grid">
                  {% for day in calendar.get_days %}
                    {% is_booked room day as is_booked_bool %}
                      {% if day.day != 0 %}
                        {% if day.past %}
                          <span class="cal-date text-gray-100">{{day}}</span>
                        {% elif is_booked_bool %}
                          <span class="cal-date text-gray-400" style="text-decoration: line-through;">{{day}}</span>
                        {% else %}
                          <a href="{% url 'reservations:create' room.pk day.year day.month day.day %}" class="cal-date text-gray-700 hover:bg-teal-400 hover:text-white hover:cursor-pointer hover:font-medium">{{day}}</a>
                        {% endif %}
                          
                      {% else %}
                        <span></span>
                      {% endif %}                    
                  {% endfor %}
                </div>
              </div>
            {% endfor %}
          {% endif %}
            
        {% endif %}
      </div>
      
    </div>
    
    <div class="py-10 border-t border-gray-200">
      <h4 class="font-semibold text-3xl mb-5">Reviews</h4>
      <div class="flex items-center">
        <div class="mr-5 flex items-center">
          <i class="fas fa-star text-red-500 mr-1"></i>
          <span class="font-bold text-xl">{{room.total_rating}}</span>
        </div>
        
        <div class="h-5 w-px bg-gray-400 mx-5"></div>
        
        <div class="">
          <span class="font-bold text-xl">{{room.reviews.count}}</span>
          <span>review{{room.reviews.count|pluralize}}</span>
        </div>
      </div>

      <div class="w-11/12 mt-10 flex justify-between flex-wrap">
        {% for review in room.reviews.all %}
          <div class="w-2/5">
            <div class="py-8 ">
              <div class="mb-3 flex items-center">
                <div class="">
                  {% include "mixins/user_avatar.html" with user=review.user h_and_w='w-14 h-14' text='text-xl' %}
                </div>
                <div class="flex flex-col ml-5">
                  <span class="font-medium">{{review.user.first_name}}</span>
                  <span class="text-sm text-gray-500">{{review.created|date:'F Y'}}</span>
                </div>
              </div>
              <p class="line-clamp-3 text-black">{{review.review}}</p>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    
  </div>  

{% endblock content %}

templates/rooms/room_edit.html
{% extends 'base.html' %}

{% block page_title %}
    Update Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}


{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-[360px] mx-auto py-8 flex flex-col justify-start border border-gray-400">
        
        {% include 'mixins/room/room_form.html' with form=form submitBtn="Edit Room" %}
        <div class="mt-5 flex justify-center">
            <a href="{% url 'rooms:photos' room.pk %}" class="text-teal-500 font-medium mb-1">Edit Photos</a>
        </div>
    </div>
{% endblock content %}

templates/rooms/room_list.html
{% extends 'base.html' %} 
{% load static %}
{% block Page_name %} 
  Home 
{% endblock Page_name %} 

{%block content %} 
  <div class="container w-11/12 mx-auto pb-10">
    
    <div class="bg-gray-800 rounded-3xl h-65vh w-full mt-32 mb-24 bg-cover bg-center" style="background-image: url({% static 'img/12.jpg' %})"></div>
    
    <div class="flex flex-wrap justify-between mb-10">
      {% for room in object_list %}
        {% include 'partials/room_card.html' with room=room %}
      {% endfor %}
    </div>
    
    <div class="flex items-center justify-center">
      {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number }}" class="text-teal-500">
          <i class="fas fa-arrow-left fa-lg"></i>
        </a>
      {% endif %}

      <span class="mx-3 font-medium text-lg">
        {{page_obj.number}} of {{page_obj.paginator.num_pages}}
      </span>
      {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number }}" class="text-teal-500">
          <i class="fas fa-arrow-right fa-lg"></i>
        </a>
      {% endif %}
    </div>
  </div>

{% endblock content %}

templates/rooms/room_photos.html
{% extends 'base.html' %}

{% block page_title %}
    {{room.name}}'s Photos
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}


{% block content %}
    <div class="container w-7/12 mx-auto flex flex-col">
        <div class="my-10 w-full">
            <a href="{% url 'rooms:add-photo' room.pk %}" class="btn w-1/3 block bg-red-500 text-white">Upload Photo</a>
        </div>

        {% for photo in room.photos.all %}
            <div class="mb-5 w-full border border-gray-400 p-10 flex justify-between">
                <div class="flex flex-col">
                    <img src="{{photo.file.url}}" class="w-44 h-44 mb-1" />
                    <span class="w-64 text-xl line-clamp-2">{{photo.caption}}</span>
                </div>
                <div class="flex flex-col items-end w-1/4 text-white">
                    <a href="{% url 'rooms:edit-photo' room.pk photo.pk %}" class="btn  px-5 bg-teal-500 my-4">Edit</a>
                    <a href="{% url 'rooms:delete-photos' room.pk photo.pk %}" class="btn  px-5 bg-red-600">Delete</a>
                </div>
            </div>
            
        {% endfor %}
        <div class="flex justify-center">
            <a href="{% url 'rooms:edit' room.pk %}" class="text-teal-500 text-xl font-medium py-4 mb-3">Back to edit room</a>
        </div>
            
    </div>
{% endblock content %}

templates/rooms/search.html
{% extends 'base.html' %}

{% block page_title %}
    Search
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <h2>Search</h2>

    <form method="get" action="{% url 'rooms:search' %}">
        {{form.as_p}}
        <button>Search</button>
    </form>

    <div>
        <h3>Results</h3>
        {% for room in rooms %}
            <h3>{{room.name}}</h3>
        {% endfor %}
    </div>

{% endblock content %}