config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),

    # path("verify/<str:key>/", views.complete_verification, name="complete-verification"),
    path("login/google/", views.google_login, name="google-login"),
    path("login/google/callback/", views.google_callback, name="google-callback"),
    # path("login/facebook/", views.facebook_login, name="facebook-login"),
    # path("login/facebook/callback/", views.facebook_callback, name="facebook-callback"),

    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.PasswordChangeView.as_view(), name="password"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.shortcuts import reverse
from django.utils.translation import gettext_lazy as _
from core import managers as core_managers

class User(AbstractUser):

    """Custom User Models"""

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_OTHER = "other"

    GENDER_CHOICES = (
        (GENDER_MALE, _("Male")),
        (GENDER_FEMALE, _("Female")),
        (GENDER_OTHER, _("Other")),
    )

    LANGUAGE_ENGLISH = "en"
    LANGUAGE_FRENCH = "fr"

    LANGUAGE_CHOICES = (
        (LANGUAGE_ENGLISH, _("English")),
        (LANGUAGE_FRENCH, _("French")),
    )

    CURRENCY_USD = "usd"
    CURRENCY_GBP = "gbp"
    CURRENCY_EUR = "eur"
    CURRENCY_INR = "inr"

    CURRENCY_CHOICES = (
        (CURRENCY_USD, _("USD")),
        (CURRENCY_INR, _("INR")),
        (CURRENCY_GBP, _("GBP")),
        (CURRENCY_EUR, _("EUR")),
    )

    LOGIN_EMAIL = "email"
    LOGIN_GOOGLE = "google"
    LOGIN_FACEBOOK = "facebook"

    LOGIN_CHOICES = (
        (LOGIN_EMAIL, "Email"),
        (LOGIN_GOOGLE, "Google"),
        (LOGIN_FACEBOOK, "Facebook"),
    )

    first_name = models.CharField(
        _("first name"), max_length=30, blank=True, default="Unnamed User"
    )
    avatar = models.ImageField(upload_to="avatars", blank=True)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=10, blank=True)
    bio = models.TextField(default="", blank=True)
    birthdate = models.DateField(blank=True, null=True)
    language = models.CharField(choices=LANGUAGE_CHOICES, max_length=2, blank=True)
    currency = models.CharField(choices=CURRENCY_CHOICES, max_length=3, blank=True)
    superhost = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=False)
    email_secret = models.CharField(max_length=20, default="", blank=True)
    login_method = models.CharField(
        max_length=50, choices=LOGIN_CHOICES, default=LOGIN_EMAIL
    )
    objects = core_managers.CustomUserManager()

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})
    

users/forms.py
from . import models
from django import forms


class LoginForm(forms.Form):

    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email Address", "class":"input w-full"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Enter Your Password", "class":"input w-full"}))

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Incorrect Password"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User does not exist"))


class SignupForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("first_name", "last_name", "email")
        widgets = {
            "first_name": forms.TextInput(attrs={"placeholder": "First Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Name"}),
            "email": forms.EmailInput(attrs={"placeholder": "Email Address"}),
        }

    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Enter Your Password"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Enter Your Password Again"}), label="Confirm Password")

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError("User with this Email already exists")
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data["password"]
        password1 = self.cleaned_data["password1"]

        if password != password1:
            raise forms.ValidationError("Passwords don't Match")
        else:
            return password

    def save(self):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()

users/views.py
import requests
from django.urls import reverse, reverse_lazy
from django.conf import settings
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import FormView, DetailView, UpdateView
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from . import forms, models, mixins
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin

class LoginView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)
    
    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        # next_arg = self.request.query_params.get('next',None)
        print(self.request.GET)
        # print(next_arg)
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def log_out(request):
    logout(request)
    messages.info(request, f"See you later")
    return redirect(reverse("core:home"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/signup.html"
    form_class = forms.SignupForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
        # to do: add succes message
    except models.User.DoesNotExist:
        # to do: add error message
        pass
    return redirect(reverse("core:home"))


def google_login(request):
    client_id = settings.GAUTH_CLIENTID
    redirect_uri = "http://127.0.0.1:8000/users/login/google/callback/"
    googleAuthUrl = 'https://accounts.google.com/o/oauth2/v2/auth'

    return redirect(
        f"{googleAuthUrl}?client_id={client_id}&redirect_uri={redirect_uri}&scope=openid%20profile%20email&response_type=code"
    )

class GoogleException(Exception):
    pass

def google_callback(request):
    try:
        redirect_uri = "http://127.0.0.1:8000/users/login/google/callback/"
        access_token_url = "https://accounts.google.com/o/oauth2/token"
        profile_url = "https://www.googleapis.com/oauth2/v1/userinfo"

        code = request.GET.get("code", None)
        if code is not None:
            data = {
            'code': code,
            'client_id': settings.GAUTH_CLIENTID,
            'client_secret': settings.GAUTH_CLIENT_SECRET,
            'redirect_uri': redirect_uri,
            'grant_type': 'authorization_code'
            }

            token_request = requests.post(access_token_url, data=data)
            token_json = token_request.json()
            error = token_json.get("error", None)
            if error is not None:
                raise GoogleException("Can't get access token")
            else:
                access_token = token_json.get("access_token")
                profile_request = requests.get(
                    profile_url,
                    params={'access_token': access_token},
                )
                user_data = profile_request.json()
                print(user_data)
                email = user_data.get("email", None)
                if email is not None:
                    first_name = user_data.get('given_name', '')
                    last_name = user_data.get('family_name', '')
                    try:
                        user = models.User.objects.get(email=email)
                        if user.login_method != models.User.LOGIN_GOOGLE:
                            raise GoogleException(
                                f"Please log in with: {user.login_method}"
                            )
                        
                    except models.User.DoesNotExist:
                        user = models.User.objects.create(
                            email=email.capitalize() ,
                            first_name=first_name.capitalize(),
                            last_name=last_name.capitalize(),
                            username=email,
                            login_method=models.User.LOGIN_GOOGLE,
                            email_verified=True,
                        )
                        user.set_unusable_password()
                        user.save()
                    login(request, user)
                    messages.success(request, f"Welcome back {user.first_name}")
                    return redirect(reverse("core:home"))
                else:
                    raise GoogleException("Can't get your profile")
        else:
            raise GoogleException("Can't get code")
    except GoogleException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


class UserProfileView(DetailView):
    model = models.User
    context_object_name = "user_obj"

    
class UpdateProfileView(mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):
    
    model = models.User
    template_name = "users/update_profile.html"
    success_message = "Profile Updated"
    fields = {
        "first_name",
        "last_name",
        "gender",
        "bio",
        "birthdate",
        "language",
        "currency",
    }

    def get_object(self, queryset=None):
        return self.request.user
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["first_name"].widget.attrs={"placeholder": "First Name"}
        form.fields["last_name"].widget.attrs={"placeholder": "Last Name"}
        form.fields["bio"].widget.attrs={"placeholder": "About You"}
        form.fields["gender"].widget.attrs={"placeholder": "Gender"}
        form.fields["birthdate"].widget.attrs={"placeholder": "Birth Date"}
        form.fields["language"].widget.attrs={"placeholder": "Language"}
        form.fields["currency"].widget.attrs={"placeholder": "Curency"}
        return form


class PasswordChangeView(mixins.LoggedInOnlyView, mixins.EmailLoginOnlyView, SuccessMessageMixin, PasswordChangeView):

    template_name = "users/update-password.html"
    success_message = "Password Updated"
 
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["old_password"].widget.attrs={"placeholder": "Current Password"}
        form.fields["new_password1"].widget.attrs={"placeholder": "New Password"}
        form.fields["new_password2"].widget.attrs={"placeholder": "Confirm New Password"}
        return form

    def get_success_url(self):
        return self.request.user.get_absolute_url()


@login_required
def switch_hosting(request):
    try: 
        del request.session["is_hosting"]
    except KeyError:
        request.session["is_hosting"] = True
    return redirect(reverse("core:home"))

templates/users/login.html
{% extends 'base.html' %}

{% block page_title %}
    Login
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}


{% block content %}
<div class="container lg:w-5/12 md:w-1/2 xl:w-[360px] mx-auto flex flex-col justify-center border border-gray-400">
        {% include "partials/social_login.html" %}
        
        <form method="POST" action="{% url 'users:login' %}" class="w-full p-1 flex flex-col items-center">
            {% csrf_token %}
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <span class="text-red-700 font-normal text-sm px-2">{{error}}</span>
                {% endfor %}
            {% endif %}

            {% for field in form %}
                <div class="w-5/6 mb-3">
                    {{field}}
                    {% if field.errors %}
                        {% for error in field.errors %}
                            <span class="text-red-700 font-normal text-sm px-2">{{error}}</span>
                        {% endfor %}
                    {% endif %}
                </div>        
            {% endfor %}
            <button class="btn bg-red-500 text-white mt-2  hover:bg-red-600">Login</button>
        
        </form>
        
        <div class="mt-5 flex justify-center">
            <span class="mr-3">Don't have an account?</span>
            <a href="{% url 'users:signup' %}" class="text-teal-500 font-medium mb-8">Sign up</a>
        </div>
    </div>
{% endblock content %}

templates/users/signup.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block page_title %}
    SignUp
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class="container lg:w-5/12 md:w-1/2 xl:w-[360px] mx-auto flex flex-col justify-center border border-gray-400">
    {% include "partials/social_login.html" %}
    <form method="POST" action="{% url 'users:signup' %}" class="w-full p-1 flex flex-col items-center">
        {% csrf_token %}
        
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <span class="text-red-700 font-normal text-sm px-2">{{error}}</span>
            {% endfor %}
        {% endif %}

        {% for field in form %}
            <div class="w-5/6 mb-3 ">
                {% if field.errors %}
                    {% for error in field.errors %}
                    {{field|add_class:"has_error"}}
                    <span class="text-red-700 font-normal text-sm px-2">{{error}}</span>
                    {% endfor %}
                {% else %}
                    {{field}}
                {% endif %}
            </div>        
        {% endfor %}

        <button class="btn bg-red-500 text-white mt-2">Sign Up</button>
    </form>
    <div class="mt-5 flex justify-center">
        <span class="mr-3">Already have an account?</span>
        <a href="{% url 'users:login' %}" class="text-teal-500 font-medium mb-8">Login</a>
    </div>
</div>
{% endblock content %}

templates/users/update-password.html
{% extends 'base.html' %}

{% block page_title %}
    Update Password
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}


{% block content %}
<div class="h-70vh">
    <div class="container lg:w-5/12 md:w-1/2 xl:w-[360px] mx-auto flex flex-col justify-center border border-gray-400">
            
            <form method="POST" action="{% url 'users:login' %}" enctype="multipart/form-data" class="w-full p-1 flex flex-col items-center mt-8">
                {% csrf_token %}
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <span class="text-red-700 font-normal text-sm px-2">{{error}}</span>
                    {% endfor %}
                {% endif %}
    
                {% for field in form %}
                    <div class="w-5/6 mb-3">
                        {{field}}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <span class="text-red-700 font-normal text-sm px-2">{{error}}</span>
                            {% endfor %}
                        {% endif %}
                    </div>        
                {% endfor %}
                <button class="btn bg-red-500 text-white mt-2  hover:bg-red-600 mb-8">Update Password</button>
            
            </form>
        </div>
</div>
{% endblock content %}

templates/users/update_profile.html
{% extends 'base.html' %}

{% block page_title %}
    Update Profile
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}


{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-[360px] mx-auto py-8 flex flex-col justify-center border border-gray-400">
        
        {% include 'mixins/form/form.html' with form=form %}

        {% if object.login_method == "email" %}
            <div class="mt-5 flex justify-center">
                <a href="{% url 'users:password' %}" class="text-teal-500 font-medium mb-1">Change Password</a>
            </div>
        {% endif %}
            
    </div>
{% endblock content %}

templates/users/user_detail.html
{% extends 'base.html' %}

{% block page_title %}
    {{user_obj.first_name}}'s Profile
{% endblock page_title %}



{% block content %}

<div class="{% if user_obj.rooms.count == 0 %}h-70vh{% endif %}">
    <div class="container lg:w-5/12 md:w-1/2 xl:w-[360px] mx-auto flex flex-col items-center justify-center border border-gray-400 py-6 mb-10">
    
        {% include "mixins/user_avatar.html" with user=user_obj %}
           
        <div class="flex items-center">
            <span class="text-3xl mt-1">{{user_obj.first_name}}</span>
            {% if user_obj.superhost %}
                <i class="fa fa-check-circle text-red-500 ml-2"></i>
            {% endif %}
        </div>
        
        <span class="text-lg {% if user_obj.superhost %}mr-2{% endif %}">{{user_obj.bio}}</span>
        
        {% if user.id == user_obj.id %}
            <a href="{% url 'users:update' %}" class="btn bg-red-500 mt-4 text-white rounded-md">Edit profile</a>
        {% endif %}
        
    </div>
    
    {% if user_obj.rooms.count > 0 %}
        <div class="container w-11/12 flex-col mx-auto pb-10">
            <div class="w-full flex justify-center">
                <div class="mb-12 text-2xl">{{user_obj.first_name}}'s Rooms</div>
            </div>
            <div class="flex flex-wrap mb-10">
                {% for room in user_obj.rooms.all %}
                    {% include 'partials/room_card.html' with room=room %}
                {% endfor %}
            </div>
        </div>
    {% endif %}
</div>
        
{% endblock content %}